# Generated by Django 5.0.3 on 2024-03-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentform',
            new_name='StudentData',
        ),
    ]
